In [1]:
import torch
import torch.nn as nn
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [2]:
%%time
start_time = time.time()
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: 10}")

 0.003213167190551758
CPU times: user 289 µs, sys: 978 µs, total: 1.27 ms
Wall time: 3.26 ms


In [3]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.41864920
0.49457002


In [4]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 0, 1, 1, 1, 1, 1, 0, 0])


In [5]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [6]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [11]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
import torch.nn as nn
sample = torch.tensor([10.,10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 6.2905,  9.8780, -8.0847], grad_fn=<SqueezeBackward4>)


In [13]:
import torch.nn.functional as F
tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [14]:
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1, 5, 3, 2])

embedded_output = embedding(input_indices)

print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 2.9818, -0.1091, -0.0958, -0.5662,  0.9463,  0.2471],
        [-0.1915,  1.1909, -0.5095, -2.1630, -1.2449, -0.5908],
        [ 0.3327, -1.7504, -1.2869, -0.5209, -0.5526, -0.0339],
        [ 0.0999,  1.1993, -0.7374,  0.4457,  0.5266, -1.3456]],
       grad_fn=<EmbeddingBackward0>)


In [15]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
#print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [16]:
int_64 = torch.randint(1, (3, 2)).float()
float_32 = torch.rand(2,3)
#print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)
#print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [18]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
print(output[:, -1, :])

tensor([[0.0492, 0.1957, 0.3417, 0.9242, 0.2919, 0.3111, 0.5369, 0.8106, 0.8750,
         0.7704],
        [0.8229, 0.3611, 0.3422, 0.6082, 0.7278, 0.5074, 0.1219, 0.5729, 0.7974,
         0.0422],
        [0.9502, 0.7188, 0.2111, 0.6254, 0.7397, 0.0549, 0.8124, 0.4552, 0.4754,
         0.5201],
        [0.6255, 0.5063, 0.0055, 0.7599, 0.2330, 0.7793, 0.0896, 0.5661, 0.7304,
         0.4178],
        [0.1559, 0.9332, 0.3625, 0.1930, 0.4525, 0.2932, 0.8670, 0.5898, 0.7790,
         0.5971],
        [0.6779, 0.9347, 0.2617, 0.9443, 0.7043, 0.9337, 0.7477, 0.4902, 0.7583,
         0.9261],
        [0.2518, 0.4163, 0.2508, 0.4157, 0.1794, 0.6279, 0.8068, 0.2584, 0.4870,
         0.3546],
        [0.1961, 0.0264, 0.3330, 0.5195, 0.7207, 0.2050, 0.3345, 0.3914, 0.4108,
         0.9372],
        [0.3416, 0.0651, 0.2581, 0.6512, 0.8277, 0.9124, 0.9970, 0.8703, 0.5515,
         0.1412],
        [0.4902, 0.8359, 0.1267, 0.0102, 0.2192, 0.0115, 0.3288, 0.5645, 0.3277,
         0.4123],
        [0

IndexError: too many indices for tensor of dimension 2

In [21]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
